### PR TITLE
add timestamp in test set

### PR DESCRIPTION
**Pull request by wywyWang**
Based on a discussion with Jacopo in Slack, this PR is mainly to add the timestamp of user history into the test set.

### CODE REVIEW

**Comment by vinid** [comment]
this looks good but I'd like to make this an optional thing (i.e., people might need to write portions of their code if we change how we create the train/test sets). 

let me do a couple of quick edits

**Comment by wywyWang** [comment]
This looks great!

**Comment by vinid** [comment]
We didn't merge this yet :), is there a reason why you closed the PR?

**Comment by wywyWang** [comment]
Oh... I deleted my forked repo a few hours ago. Didn't notice it would close this. Let me reopen this.

**Comment by wywyWang** [comment]
I noticed that it would have errors when evaluating (became normal if removing the timestamp in the test set). It seems the evaluation codes also need to be modified.

The error occurred in `miss_rate_at_k_slice` in `EvalRSRecList.py`.
The exact error code is
```
m = pd.DataFrame(m, columns=['mr'], index=y_test.index)
```
The error message is 
```
ValueError: Shape of passed values is (26330, 2), indices imply (26330, 1)
```

**Comment by vinid** [comment]
might make sense to have this only for training data?

**Comment by radekosmulski** [comment]
One thing that might be of some concern here is whether adding this information to the test set wouldn't change the nature of the problem. This brings a new dimension to the challenge as we can search for songs listened to before and after the song that we are now trying to predict. It becomes a context-aware recommendation of sorts.

Not sure if that is a bad thing or a good thing, or how far other people are in working on their solution (this might be a change that could dictate a change in approach), but thought I'd raise this for consideration 🙂

**Pull request merged**
